name: PlayerDataRollback
version: 2.1.4-GA
main: link.star_dust.PlayerDataRollback.PlayerData
api-version: 1.13
description: Allow you creata playerdata buckup and rollback playerdata
commands:
  playerdata:
    description: Plugin's main command
    aliases: [pld, pldr, playerdatarollback]
    usage: "/playerdata <command>"
    permission: playerdata.use
permissions:
  playerdata.reload:
    description: Allows the player to reload the plugin configuration
    default: op
  playerdata.rollback:
    description: Allows the player to rollback backup
    default: op
  playerdata.rollbackall:
    description: Allows the player to rollback all backups
    default: op
  playerdata.backup.remove:
    description: Allows the player to remove backups, required playerdata.backup permission
    default: op
  playerdata.backup.removeall:
    description: Allows the player to remove all backups, required playerdata.backup permission
    default: op
  playerdata.backup.create:
    description: Allows the player to create backups, required playerdata.backup permission
    default: op
  playerdata.backup:
    description: Basic backup command permission
    default: op
  playerdata.help:
    description: Allows the player to get the plugin's help
    default: op
  playerdata.list:
    description: Allows the player to list all backups
    default: op
  playerdata.checkupdate:
    description: Allows the player get update messages
    default: op
